# Generated by Django 5.2.17 on 2026-08-10 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('passed_checks', models.PositiveIntegerField(default=0)),
                ('failed_checks', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='datasets_app.dataset')),
            ],
        ),
    ]
