# Generated by Django 5.2.17 on 2026-08-10 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('row_number', models.PositiveBigIntegerField()),
                ('issue_type', models.CharField(choices=[('missing', 'Missing Value'), ('duplicate', 'Duplicate Value'), ('invalid', 'Invalid Value'), ('format', 'Invalid Format'), ('range', 'Out of Range')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('value', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='validation.validationrun')),
            ],
        ),
    ]
