# Generated by Django 5.2.17 on 2026-08-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_dataissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('completeness', 'Completeness'), ('uniqueness', 'Uniqueness'), ('validity', 'Validity'), ('format', 'Format'), ('consistency', 'Consistency'), ('range', 'Range')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
