# Generated by Django 5.2.17 on 2026-08-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_validationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrule',
            name='column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='rule_type',
            field=models.CharField(blank=True, choices=[('missing', 'Missing Value'), ('duplicate', 'Duplicate'), ('range', 'Range'), ('format', 'Format'), ('invalid', 'Invalid Value')], max_length=30, null=True),
        ),
    ]
